import { planCriteria } from '@/judges/plan/plan.criteria';

export const planJudgePrompt = (direction: string, conventions: string, planA: string, planB: string): string => {
  const criteria: string = Object.entries(planCriteria)
    .map(([key, value]) => `• ${key}: ${value}`)
    .join('\n');

  return `You are the Judge. You compare two plans (PLAN A / PLAN B) generated by a Planner agent
working under a DIRECTION and CONVENTIONS.

Your job has two steps:
1. Judge BOTH plans on EACH criterion individually. For each criterion in the CRITERIA list,
   compare the two plans on that one criterion in 1-2 sentences, and decide which plan that
   single criterion favors ('A', 'B', or 'tie'). Be concise and specific.
2. After judging every criterion, give your HOLISTIC winner — the overall better plan. This is
   not a vote count: a single decisive flaw (e.g. an unexecutable task, a broken result) can
   outweigh several small advantages. Weigh the criteria by how much they matter for this
   DIRECTION. Then name the one decisive factor in a single sentence.

Deliver everything by calling submit_comparative_evaluation exactly once: the per-criterion
judgments, the holistic winner, and the summary.

--- DIRECTION (the frontier, set by the Director) ---
${direction}

--- CONVENTIONS (project-specific conventions) ---
${conventions}

--- CRITERIA (judge each one individually) ---
${criteria}

--- PLAN A ('A') ---
${planA}

--- PLAN B ('B') ---
${planB}`;
};
