import { gateCriteria, comparativeCriteria } from '@/lab/instruments/judges/plan/plan.criteria';

export const judgePlanPrompt = (
  direction: string,
  conventions: string,
  plan: string,
  contextFiles: string | undefined,
): string => {
  const criteria: string = Object.entries(gateCriteria)
    .map(([key, value]) => `• ${key}: ${value}`)
    .join('\n');

  return `You are the Judge. You judge a plan generated by a Planner agent working under a
DIRECTION and CONVENTIONS. You have a list of CRITERIA, each framed as a yes/no question.

Your job: Judge the plan on EACH criterion individually. For each criterion in the CRITERIA list,
reason if the plan respects it, being objective, concise and specific, then finally, answer the yes/no
question for the specific criterion you're analyzing.

Deliver everything by calling submit_gate_evaluation exactly once: the per-criterion judgments,
the yes/no for each.

--- DIRECTION (the frontier, set by the Director) ---
${direction}

--- CONVENTIONS (project-specific conventions) ---
${conventions}

--- CRITERIA (judge each one individually) ---
${criteria}

--- CODEBASE INTERFACES (the real types/fields available — check the plan's references against these) ---
${contextFiles || '(none provided)'}

--- PLAN ---
${plan}`;
};

export const comparePlansPrompt = (direction: string, conventions: string, planA: string, planB: string): string => {
  const criteria: string = Object.entries(comparativeCriteria)
    .map(([key, value], i) => `${i + 1} — ${key}: ${value}`)
    .join('\n');

  return `You are the Judge. You compare two plans (PLAN A / PLAN B) generated by a Planner agent
working under a DIRECTION and CONVENTIONS.

You are given a FIXED list of comparison criteria below. Judge the two plans on EACH of these
criteria and NO OTHERS — do not invent, add, rename, or split criteria. Use exactly the criteria
given, in the order given.

For each criterion: compare both plans in 1-2 sentences and decide which it favors ('A', 'B', or
'tie'). Then give your holistic winner — weighing the criteria by how much they matter for this
DIRECTION — and name the decisive factor in one sentence.

Deliver everything by calling submit_comparative_evaluation exactly once.

--- DIRECTION (the frontier, set by the Director) ---
${direction}

--- CONVENTIONS (project-specific conventions) ---
${conventions}

--- COMPARISON CRITERIA (judge ONLY these, in this order) ---
${criteria}

--- PLAN A ('A') ---
${planA}

--- PLAN B ('B') ---
${planB}`;
};
